<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bienvenue sur mon blog</title>
</head>
<body>
    <header>
        <h1>Mon super blog !</h1>
        <nav>
            <a href="home.php">Accueil</a>
            <?php if (isConnected()): ?>
                <span><?=htmlspecialchars(getUserFirstname());?> <?=htmlspecialchars(getUserLastname());?></span>
                <a href="logout.php">Déconnexion</a>
            <?php else: ?>
                <a href="login.php">Connexion</a>
                <a href="signup.php">Créer un compte</a>
            <?php endif; ?>
        </nav>
    </header>
    <main>
        <?php include '../templates/' . $template . '.phtml'; ?>
    </main>
</body>
</html>